FROM python:3.11-slim

RUN apt-get update && apt-get install -y tzdata ca-certificates

WORKDIR /app
COPY . .

RUN pip install --no-cache-dir -r requirements.txt

ENV TZ=Europe/Kyiv

CMD ["python", "main.py"]